export const characterData = {
  info: {
    name: "Frank Howard",
    player: "Bob",
    occupation: "Detective",
    age: 47,
    sex: "Male",
    residence: "Chicago",
    birthplace: "Chicago",
  },
  characteristics: {
    str: 50,
    con: 70,
    siz: 75,
    dex: 60,
    app: 50,
    edu: 60,
    int: 70,
    pow: 55,
    mov: 6,
  },
  pinnedSkills: [],
  skills: [
    { skill: "Accounting", baseValue: 5 },
    { skill: "Animal Handling (Uncommon)", baseValue: 5 },
    { skill: "Anthropology", baseValue: 1 },
    { skill: "Appraise", baseValue: 5 },
    { skill: "Archaeology", baseValue: 1 },
    { skill: "Art and Craft (Specializations)", baseValue: 5 },
    { skill: "Artillery (Uncommon)", baseValue: 1 },
    { skill: "Charm", baseValue: 15 },
    { skill: "Climb", baseValue: 20 },
    { skill: "Computer Use (Modern)", baseValue: 5 },
    { skill: "Credit Rating", baseValue: 0 },
    { skill: "Cthulhu Mythos", baseValue: 0 },
    { skill: "Demolitions (Uncommon)", baseValue: 1 },
    { skill: "Disguise", baseValue: 5 },
    { skill: "Diving (Uncommon)", baseValue: 1 },
    { skill: "Dodge", baseValue: "1/2 DEX" },
    { skill: "Drive Auto", baseValue: 20 },
    { skill: "Electrical Repair", baseValue: 10 },
    { skill: "Electronics (Modern)", baseValue: 1 },
    { skill: "Fast Talk", baseValue: 5 },
    { skill: "Fighting (Specializations)", baseValue: 20 },
    { skill: "Firearms (Specializations)", baseValue: 25 },
    { skill: "First Aid", baseValue: 30 },
    { skill: "History", baseValue: 5 },
    { skill: "Hypnosis (Uncommon)", baseValue: 1 },
    { skill: "Intimidate", baseValue: 15 },
    { skill: "Jump", baseValue: 20 },
    { skill: "Language, Other (Specializations)", baseValue: 1 },
    { skill: "Language (Own)", baseValue: "EDU" },
    { skill: "Law", baseValue: 5 },
    { skill: "Library Use", baseValue: 20 },
    { skill: "Listen", baseValue: 20 },
    { skill: "Locksmith", baseValue: 1 },
    { skill: "Lore (Specializations) (Uncommon)", baseValue: 10 },
    { skill: "Mechanical Repair", baseValue: 10 },
    { skill: "Medicine", baseValue: 1 },
    { skill: "Natural World", baseValue: 10 },
    { skill: "Navigate", baseValue: 10 },
    { skill: "Occult", baseValue: 5 },
    { skill: "Operate Heavy Machinery", baseValue: 1 },
    { skill: "Persuade", baseValue: 10 },
    { skill: "Pilot (Specializations)", baseValue: 1 },
    { skill: "Psychoanalysis", baseValue: 1 },
    { skill: "Psychology", baseValue: 10 },
    { skill: "Read Lips (Uncommon)", baseValue: 1 },
    { skill: "Ride", baseValue: 5 },
    { skill: "Science (Specializations)", baseValue: 1 },
    { skill: "Sleight of Hand", baseValue: 10 },
    { skill: "Spot Hidden", baseValue: 25 },
    { skill: "Stealth", baseValue: 20 },
    { skill: "Survival (Specializations)", baseValue: 10 },
    { skill: "Swim", baseValue: 20 },
    { skill: "Throw", baseValue: 20 },
    { skill: "Track ", baseValue: 10 },
  ],
  status: {
    hitpoints: {
      current: 12,
      max: 12,
    },
    magicPoints: {
      current: 12,
      max: 12,
    },
    sanity: {
      current: 15,
      max: 15,
    },
    luck: 80,
  },
  combatStats: {
    damageBonus: 0,
    build: 0,
    dodge: 0,
  },
  backstory: {
    personalDescription: "dummy data",
    ideologyAndBeliefs: "",
    significantPeople: "",
    meaningfulLocations: "",
    treasuredPossessions: "",
    traits: "",
    injuriesAndScars: "",
    phobiasAndManias: "",
  },
  possessions: {
    weapons: [
      {
        name: ".38 Revolver",
        skill: "Firearms (handgun)",
        damage: "1D10",
        baseRange: 15,
        usesPerRound: "1 (3)",
        capacity: 6,
        malfunction: 100,
      },
      {
        name: "Small Knife",
        skill: "Fighting (Brawl)",
        damage: "1D4+DB",
        baseRange: "Touch",
        usesPerRound: 1,
        capacity: "-",
        malfunction: "-",
      },
    ],
    possessions: [],
    wealth: [],
    assets: [],
  },
};
